### ISSUE TITLE
[ Feature Request ] Add link to Nethack Wiki for entry

### ISSUE THREAD

**Issue by graves501** [ZeroOne3010/nethackmonsters#1]
Hi, 

I really enjoy this project! 

For convenience it would be nice if the items/monsters would have a clickable link to the appropriate Nethack Wiki article :)

**Comment by ZeroOne3010** [comment]
Hey, thank you for your feedback, and for opening the very first issue in this project! 😃 That's actually a great idea, it will go to the top of my to do list! 👌

**Comment by graves501** [comment]
@ZeroOne3010 

Thank you so much for implementing this! It's especially great for beginners and the artwork is amazing! Have a nice day!
